'use client';
import { useCallback,useEffect,useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { AlertTriangle,ArrowLeft,CheckCircle2,Clock3,ShieldAlert } from 'lucide-react';

interface ExceptionCard{id:string;task_id:string;title:string;type:string;authority_scope:string;decision_version:number;severity:'P0'|'P1'|'P2';impact:string;recommendation:string;due_at:string|null;first_seen_at:string}
export default function CeoExceptionsPage(){
  const {slug}=useParams<{slug:string}>();const [workspace,setWorkspace]=useState<any>();const [items,setItems]=useState<ExceptionCard[]>([]);const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);const workspaceRes=await fetch(`/api/workspaces/${slug}`);if(!workspaceRes.ok){setLoading(false);return;}const ws=await workspaceRes.json();setWorkspace(ws);const response=await fetch(`/api/ceo/exceptions?workspace=${encodeURIComponent(ws.id)}`);if(response.ok)setItems(await response.json());setLoading(false);},[slug]);
  useEffect(()=>{load();},[load]);
  const acknowledge=async(item:ExceptionCard)=>{await fetch(`/api/exceptions/${item.id}/actions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idempotency_key:`dashboard:${item.id}:${item.decision_version}:ack`,expected_decision_version:item.decision_version,action:'acknowledge'})});await load();};
  return <div className="min-h-screen bg-mc-bg text-mc-text"><header className="border-b border-mc-border bg-mc-bg-secondary"><div className="max-w-6xl mx-auto p-4 flex items-center justify-between"><div><h1 className="text-xl font-bold">CEO Exceptions</h1><p className="text-sm text-mc-text-secondary">Decisions, blockers and overdue commitments only</p></div><Link href={`/workspace/${slug}`} className="flex items-center gap-2 text-sm text-mc-text-secondary hover:text-mc-text"><ArrowLeft className="w-4 h-4"/>Mission Queue</Link></div></header>
  <main className="max-w-6xl mx-auto p-4 sm:p-6">{loading?<p className="text-mc-text-secondary">Refreshing exception projection…</p>:items.length===0?<div className="border border-mc-border bg-mc-bg-secondary rounded-xl p-10 text-center"><CheckCircle2 className="w-10 h-10 text-emerald-400 mx-auto mb-3"/><h2 className="font-semibold">No CEO exceptions</h2><p className="text-sm text-mc-text-secondary mt-1">Routine progress is intentionally suppressed.</p></div>:<div className="space-y-4">{items.map(item=><article key={item.id} className="border border-mc-border bg-mc-bg-secondary rounded-xl p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><div className={`p-2 rounded-lg ${item.severity==='P0'?'bg-red-500/20 text-red-400':'bg-amber-500/20 text-amber-400'}`}>{item.type==='overdue'?<Clock3 className="w-5 h-5"/>:item.type==='decision_required'?<ShieldAlert className="w-5 h-5"/>:<AlertTriangle className="w-5 h-5"/>}</div><div><div className="flex flex-wrap items-center gap-2"><span className={`text-xs font-bold ${item.severity==='P0'?'text-red-400':'text-amber-400'}`}>{item.severity}</span><span className="text-xs uppercase tracking-wide text-mc-text-secondary">{item.type.replaceAll('_',' ')}</span></div><h2 className="font-semibold mt-1">{item.title}</h2></div></div><button onClick={()=>acknowledge(item)} className="px-3 py-2 border border-mc-border rounded-lg text-sm hover:bg-mc-bg-tertiary">Acknowledge</button></div><p className="mt-4">{item.impact}</p><div className="mt-3 rounded-lg bg-mc-bg-tertiary p-3 text-sm"><span className="text-mc-text-secondary">Recommendation: </span>{item.recommendation}</div>{item.due_at&&<p className="text-xs text-mc-text-secondary mt-3">Due {new Date(item.due_at).toLocaleString()}</p>}</article>)}</div>}</main></div>;
}
